# 1. ??????? (???????? IP)
spring.datasource.url=jdbc:mysql://localhost:3306/allbetter_xueguan?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai

# 2. ????????? (????????????)
spring.datasource.username=root
spring.datasource.password=200504

# 3. ???? (MySQL 8 ????)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. ???
server.port=8081

# 5. ??????????????????? SQL ??
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl